pub_cache:
  folder: ~/.pub-cache

format_task:
  name: Verify formatting
  container:
    image: ghcr.io/cirruslabs/flutter:stable
  format_script: dart format . --set-exit-if-changed

analyzer_task:
  name: Run analyzer
  container:
    image: ghcr.io/cirruslabs/flutter:stable
  analyze_script:
    - flutter pub get
    - flutter analyze --no-pub

tests_task:
  name: Run tests
  container:
    image: ghcr.io/cirruslabs/flutter:stable
  test_script: flutter test

example_android_task:
  name: Build example app (Android)
  container:
    image: ghcr.io/cirruslabs/flutter:stable
  build_script:
    - cd example
    - flutter build apk --debug

example_ios_task:
  name: Build example app (iOS)
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.3.1
  build_script:
    - cd example
    - flutter build ios --no-codesign --debug
