name: siri_wave
description: >
  A Flutter package that lets you create visually stunning Siri-style waveforms.
version: 2.1.0
repository: https://github.com/halildurmus/siri_wave
issue_tracker: https://github.com/halildurmus/siri_wave/issues

screenshots:
  - description: Example of the iOS 9 Siri-style waveform.
    path: gifs/ios_9.gif
  - description: Example of the iOS 7 Siri-style waveform.
    path: gifs/ios_7.gif

topics:
  - wave
  - waveform
  - siri

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
