name: siri_wave

on:
  pull_request:
    paths:
      - .github/workflows/siri_wave.yml
      - lib/**
      - test/**
      - pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/siri_wave.yml
      - lib/**
      - test/**
      - pubspec.yaml

jobs:
  build:
    uses: halildurmus/workflows/.github/workflows/flutter.yml@main
    with:
      format_directories: lib test

  dartdoc:
    needs: [build]
    uses: halildurmus/workflows/.github/workflows/dartdoc.yml@main
    with:
      use_flutter: true

  pana:
    needs: [build]
    uses: halildurmus/workflows/.github/workflows/pana.yml@main
